# Generated by Django 3.0.3 on 2020-03-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default=None, max_length=50, null=True, verbose_name="Full name"
            ),
        ),
    ]
