# Generated by Django 3.0.3 on 2020-02-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_auto_20200229_1444"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "categoria", "verbose_name_plural": "categorias"},
        ),
    ]
