# Generated by Django 3.0.3 on 2020-03-01 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_auto_20200229_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Identifier unique"
            ),
        ),
    ]
