# Generated by Django 3.0.3 on 2020-03-01 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todolist_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Identifier unique"
            ),
        ),
    ]
